import * as express from "express";

import userV2Routes from "../Features/user/route/user.v2.route"; 
import courseV2Routes from "../Features/course/route/course.v2.route";
import adminCourseV2Routes from "../Features/course/route/admin.course.v2.route";
import categoryV2Routes from "../Features/category/route/category.v2.route";
import adminCategoryV2Routes from "../Features/category/route/admin.category.v2.route";
import feedbackRoutes from "../Features/feedback/route/feedback.v2.route";
import adminFeedbackRoutes from "../Features/feedback/route/admin.feedback.v2.route";
import requestRoutes from "../Features/request/route/request.v2.route";
import adminRequestRoutes from "../Features/request/route/admin.request.v2.route";
import windowsRoutes from "../Features/windows/route/windows.v2.route";
import quizRoutes from "../Features/quiz/route/quiz.v2.route";
import adminQuizRoutes from "../Features/quiz/route/admin.quiz.v2.route";
import flashcardRoutes from "../Features/flashcard/route/flashcard.v2.route";
import adminFlashcardRoutes from "../Features/flashcard/route/admin.flashcard.v2.route";
import mslAiRoutes from "../Features/mslAi/route/mslAi.v2.route";
import adminMslAiRoutes from "../Features/mslAi/route/admin.mslAi.v2.route";
import geminiAiRoutes from "../Features/geminiAi/route/geminiAi.v2.route";
import adminGeminiAiRoutes from "../Features/geminiAi/route/admin.geminiAi.v2.route";
import gamificationRoutes from "../Features/gamification/route/gamification.v2.route";
import adminLessonRoutes from "../Features/lesson/route/admin.lesson.v2.route";
import lessonRoutes from "../Features/lesson/route/lesson.v2.route";
import adminUserRoutes from "../Features/user/route/admin.user.v2.route";
import systemRoutes from "../Features/system/route/system.route";
import adminEnrolmentRoutes from "../Features/enrolment/route/admin.enrolment.v2.route";
import adminAnalyticsRoutes from "../Features/analytics/route/admin.analytics.v2.route";
import adminLogRoutes from "../Features/logs/route/admin.log.v2.route";
import adminFaqRoutes from "../Features/faqs/route/admin.faq.v2.route";
import paymentRoutes from "../Features/payments/route/payment.v2.route";
import adminPaymentRoutes from "../Features/payments/route/admin.payment.v2.route";
const Router = express.Router();

Router.use("/user", userV2Routes);
Router.use("/course", courseV2Routes);
Router.use("/admin/course", adminCourseV2Routes);
Router.use("/category", categoryV2Routes);
Router.use("/admin/category", adminCategoryV2Routes);
Router.use("/feedback", feedbackRoutes);
Router.use("/admin/feedback", adminFeedbackRoutes);
Router.use("/request", requestRoutes);
Router.use("/admin/request", adminRequestRoutes);
Router.use("/windows", windowsRoutes);
Router.use("/quiz", quizRoutes);
Router.use("/admin/quiz", adminQuizRoutes);
Router.use("/flashcard", flashcardRoutes);
Router.use("/admin/flashcard", adminFlashcardRoutes);
Router.use("/msl-ai", mslAiRoutes);
Router.use("/admin/msl-ai", adminMslAiRoutes);
Router.use("/gemini-ai", geminiAiRoutes);
Router.use("/admin/gemini-ai", adminGeminiAiRoutes);
Router.use("/gamification", gamificationRoutes);
Router.use("/admin/lesson", adminLessonRoutes);
Router.use("/lesson", lessonRoutes);
Router.use("/admin/user", adminUserRoutes);
Router.use("/system", systemRoutes);
Router.use("/admin/enrolment", adminEnrolmentRoutes);
Router.use("/admin/analytics", adminAnalyticsRoutes);
Router.use("/admin/logs", adminLogRoutes);
Router.use("/admin/faq", adminFaqRoutes);
Router.use("/admin/payment", adminPaymentRoutes);
Router.use("/payment", paymentRoutes);


export { Router as v2Router };
